(function(d){if(!/(linkbio\.co|instabio\.cc|fans\.link|fanlnk\.to|shoplinks\.to|instabio\.to|fotoee\.com|localhost)$/gi.test(location.hostname)){location.href="https://instabio.cc";return;}
if(!String.prototype.Format){String.prototype.Format=function(){var result=this;if(arguments.length>0){for(var i=0;i<arguments.length;i++){if(arguments[i]==null)arguments[i]='';var reg=new RegExp("(\\{"+i+"\\})","g");result=result.replace(reg,arguments[i]);}}
return result;};}
if(!String.prototype.Compile){String.prototype.Compile=function(obj){return this.replace(/\{([\w ]+)\}/g,function($1,$2){return(obj!=null?obj[$2]:void 0)==undefined?"":obj[$2];});};}
function isEmpty(v){return(v===undefined||v===null||v==='');}
var BIO_ALIAS_2_CSS={'body':'body','bodyCls':'.body','bgImg':'.bg div,.bg','pageBg':'section .content','avatar':'.center .avatar','avatarImg':'.center .avatar img','brand':'.text h3','brandDesc':'.desc','button':'.item:nth-child(n),a.item:nth-child(n),.button-item:nth-child(n) .item','icon':'.item span,.item>img','link':'.item .btn .btn-text, .item .btn-text .link-text',"buttonFont":'.item .btn,.text','background':'background','backgroundColor':'background-color','backgroundImage':'background-image','fontSize':'font-size','color':'color','borderRadius':'border-radius','link-color':'.item .link-text,.item .btn-text .link-text',};var BIO_Theme_2_CSS_Text={'font':'body,.text,section,section .content{font-family:"{0}";}','font-family':'body,.text,section,section .content{font-family:"{0}";}','color':`body{
    --link-text-color:{0};
    --link-text-title-color:{0};
    --link-text-desc-color:{0};
    --link-text-button-color:{0};
}
.container,.container section{color:{0}!important;}
.header h6,.text-ctm h3,.text-ctm .desc,.item-header,.text-ctm .title,.text-ctm .subtitle,.text-ctm .title-box,.text-ctm .desc-box,.text-ctm,.pro-detail_box .title_box,.pro-detail_box .desc_box{color:{0};}
.text-ctm{color:{0};}`,font1:'body,body .center{font-family:{0};--link-font:{0};}',color1:`body{--link-title-color:{0};--link-desc-color:{0};
        --link-social-border-color:{0};--link-social-color:{0};
        --link-text-title-color:var(--link-title-color);
        --link-text-desc-color:var(--link-title-color);
    }
    .header h6,.text-ctm h3,.text-ctm .desc,.item-header,.text-ctm .title,.text-ctm .subtitle,.text-ctm .title-box,.text-ctm .desc-box,.text-ctm,.pro-detail_box .title_box,.pro-detail_box .desc_box{color:{0};}
    `,},BIO_Theme_2_CSS_Background={'color':'.bg div{background-image:initial;background-color:{0};}.bg video{display:none}','container':{'color':'.container{background-color:{0};}',},'gradient':{'gradient.style.flat':'--link-background-gradient-style:to right;','gradient.style.up':'--link-background-gradient-style:to bottom;','gradient.style.down':'--link-background-gradient-style:to top;','gradient.color.default':'','gradient.color.color1':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #EF629F, #EECDA3)}.bg video{display:none}`,'gradient.color.color2':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #F64F59, #C471ED, #12C2E9)}.bg video{display:none}`,'gradient.color.color3':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #FDBB2D, #22C1C3)}.bg video{display:none}`,'gradient.color.color4':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #1D2671, #C33764)}.bg video{display:none}`,'gradient.color.color5':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #2C3E50, #BDC3C7)}.bg video{display:none}`,'gradient.color.color6':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #B91D73, #F953C6)}.bg video{display:none}`,'gradient.color.color7':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #C6FFDD, #FBD786, #F7797D)}.bg video{display:none}`,'gradient.color.color8':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #0083B0, #00B4DB)}.bg video{display:none}`,'gradient.color.color9':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #185A9D, #43CEA2)}.bg video{display:none}`,'gradient.color.color10':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #870000, #190A05 35%)}.bg video{display:none}`,'gradient.color.color11':`.bg div{background-image:linear-gradient(var(--link-background-gradient-style), #EEF2F3, #8E9EAB)}.bg video{display:none}`,},'image':{'style':{'default':'.css-null{{0}}','gallery':`body{background:rgba(0,0,0,0);}
.bg div{
    background-image: linear-gradient(rgba(0, 0, 0, var(--link-background-image-opacity)),rgba(0, 0, 0, var(--link-background-image-opacity))), url({0});
    -webkit-filter: blur(var(--link-background-image-blur));
    -moz-filter: blur(var(--link-background-image-blur));
    -ms-filter: blur(var(--link-background-image-blur));
    filter: blur(var(--link-background-image-blur));
    transform: scale(1.05);
    background-size: cover;
    background-position: center;
}.bg video{display:none}`,'upload':`body{background:rgba(0,0,0,0);}
.bg div{
    background-image: linear-gradient(rgba(0, 0, 0, var(--link-background-image-opacity)),rgba(0, 0, 0, var(--link-background-image-opacity))), url({0});
    -webkit-filter: blur(var(--link-background-image-blur));
    -moz-filter: blur(var(--link-background-image-blur));
    -ms-filter: blur(var(--link-background-image-blur));
    filter: blur(var(--link-background-image-blur));
    background-size: cover;
    background-position: center;
}.bg video{display:none}`,},'blur':'--link-background-image-blur:{0}px;','opacity':'--link-background-image-opacity:{0};',},'video':{'coverr':`body{background:rgba(0,0,0,0);}
        .bg div{
            background-image: linear-gradient(rgba(0, 0, 0, 0),rgba(0, 0, 0, 0)), url({0});
            -webkit-filter: blur(0);
            -moz-filter: blur(0);
            -ms-filter: blur(0);
            filter: blur(0);
            background-size: cover;
            background-position: center;
            transform: scale(1);
            width:100%;
            height:100%;
            top:0;
            left:0;
        }
        .bg video{display:inline-block}`,},},BIO_Theme_2_CSS_Button={'buttonStyle':{'backgroundColor':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px;}
.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important}
.button-item:nth-child(n) .item{background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-bg-border-color)!important;border-radius:0!important;color:var(--link-button-font-color)!important;box-shadow:none}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover{background-color:var(--link-button-border-bg-color)!important;border:2px solid var(--link-button-border-color)!important;color:var(--link-button-border-font-color)!important;box-shadow:none;transform:none}
.button-item:nth-child(n) .item:hover .btn .btn-text,.button-item:nth-child(n) .item:hover .btn-text .link-text{color:var(--link-button-border-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color);}`,'backgroundColorRadius':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px;}
.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important}
.button-item:nth-child(n) .item{border-radius:var(--link-button-radius12, 8px)!important;background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-bg-border-color)!important;color:var(--link-button-font-color)!important;box-shadow:none}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover{background-color:var(--link-button-border-bg-color)!important;border:2px solid var(--link-button-border-color)!important;color:var(--link-button-border-font-color)!important;box-shadow:none;transform:none}
.button-item:nth-child(n) .item:hover .btn .btn-text,.button-item:nth-child(n) .item:hover .btn-text .link-text{color:var(--link-button-border-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color);}`,'backgroundColorRadius50':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px;}
.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important}
.button-item:nth-child(n) .item{border-radius:50vh!important;background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-bg-border-color)!important;color:var(--link-button-font-color)!important;box-shadow:none}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover{background-color:var(--link-button-border-bg-color)!important;border:2px solid var(--link-button-border-color)!important;color:var(--link-button-border-font-color)!important;box-shadow:none;transform:none}
.button-item:nth-child(n) .item:hover .btn .btn-text,.button-item:nth-child(n) .item:hover .btn-text .link-text{color:var(--link-button-border-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color);}`,'backgroundColorBorder':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px;}
.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important;background-color:rgba(0,0,0,0)!important;}
.button-item:nth-child(n) .item{border-radius:0!important;background-color:var(--link-button-border-bg-color)!important;border:2px solid var(--link-button-border-color)!important;color:var(--link-button-border-font-color)!important;box-shadow:none;}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-border-font-color)!important;}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color);}
.button-item:nth-child(n) .item:hover{background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-bg-border-color)!important;color:var(--link-button-font-color)!important;box-shadow:none;transform:none}
.button-item:nth-child(n) .item:hover .btn .btn-text,.button-item:nth-child(n) .item:hover .btn-text .link-text{color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn-icon span{border:2px solid var(--link-button-bg-thumbnail-border-color);color:var(--link-button-bg-thumbnail-color);}`,'backgroundColorBorderRadius':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px;}
.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important;background-color:rgba(0,0,0,0)!important;}
.button-item:nth-child(n) .item{border-radius:var(--link-button-radius12, 8px)!important;background-color:var(--link-button-border-bg-color)!important;border:2px solid var(--link-button-border-color)!important;color:var(--link-button-border-font-color)!important;box-shadow:none;}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-border-font-color)!important;}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color);}
.button-item:nth-child(n) .item:hover{background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-bg-border-color)!important;color:var(--link-button-font-color)!important;box-shadow:none;transform:none}
.button-item:nth-child(n) .item:hover .btn .btn-text,.button-item:nth-child(n) .item:hover .btn-text .link-text{color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn-icon span{border:2px solid var(--link-button-bg-thumbnail-border-color);color:var(--link-button-bg-thumbnail-color);}`,'backgroundColorBorderRadius50':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px;}
.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important;background-color:rgba(0,0,0,0)!important;}
.button-item:nth-child(n) .item{border-radius:50vh!important;background-color:var(--link-button-border-bg-color)!important;border:2px solid var(--link-button-border-color)!important;color:var(--link-button-border-font-color)!important;}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-border-font-color)!important;}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color);}
.button-item:nth-child(n) .item:hover{background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-bg-border-color)!important;color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn .btn-text,.button-item:nth-child(n) .item:hover .btn-text .link-text{color:var(--link-button-font-color)!important;}
.button-item:nth-child(n) .item:hover .btn-icon span{border:2px solid var(--link-button-bg-thumbnail-border-color);color:var(--link-button-bg-thumbnail-color);}`,'style1.border':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px}
.item-style .ctm-style::after,.item-style .ctm-style::before,.item-style::after,.item-style::before{display:none;background:0 0;transform:none;border:0}
.item-style .ctm-style{border:0!important;background-color:rgba(0,0,0,0)!important}
.button-item:nth-child(n) .item-style{background-color:rgba(0,0,0,0)!important;border-radius:0!important;border:2px solid var(--link-button-border-color)!important;box-shadow:none;}
.item-style:hover{box-shadow:none;transform:none}
.item-style .ctm-style{border-bottom:2px solid var(--link-button-border-color)!important}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color)}`,'style2.background':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px}
.item-style .ctm-style::after,.item-style .ctm-style::before,.item-style::after,.item-style::before{display:none;background:0 0;transform:none;border:0}
.item-style .ctm-style{border:0!important}
.button-item:nth-child(n) .item-style{background-color:rgba(0,0,0,0)!important;border-radius:0!important;border:2px solid var(--link-button-bg-color)!important;box-shadow:none;}
.item-style:hover{box-shadow:none;transform:none}
.item-style .ctm-style{margin:3px;border:0;background-color:var(--link-button-bg-color)!important}
.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:var(--link-button-font-color)!important}
.button-item:nth-child(n) .item-style .ctm-style:hover{background-color:rgba(0,0,0,0)!important}
.button-item:nth-child(n) .item-style .ctm-style:hover .btn-text,.button-item:nth-child(n) .item-style .ctm-style:hover .link-text{color:var(--link-button-border-font-color)!important}
.button-item:nth-child(n) .item-style .ctm-style:hover .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color)}`,'style3.border':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px}
.item-style .ctm-style::after,.item-style .ctm-style::before,.item-style::after,.item-style::before{display:none;background:0 0;transform:none;border:0}
.item-style .ctm-style{border:0!important}
.button-item:nth-child(n) .item-style{background-color:rgba(0,0,0,0)!important;border-radius:0!important;border:2px solid transparent!important;box-shadow:none;}
.item-style:hover{box-shadow:none;transform:none}
.item-style::before{position:absolute;top:0;left:0;content:"";display:block;width:40px;height:32px;border:2px solid var(--link-button-border-color);border-bottom:0!important;border-right:0!important}
.item-style::after{position:absolute;bottom:0;right:0;content:"";display:block;width:40px;height:32px;border:2px solid var(--link-button-border-color);border-top:0!important;border-left:0!important}
.item-style .ctm-style{margin:5px;background-color:rgba(0,0,0,0)!important;border-radius:0;border:2px solid var(--link-button-border-color)!important}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color)}`,'style4.border':`.cmpt-button-buttonLink .show-sortNum::before{left:-30px}
.item-style .ctm-style::after,.item-style .ctm-style::before,.item-style::after,.item-style::before{display:none;background:0 0;transform:none;border:0}
.item-style .ctm-style{border:0!important;background-color:rgba(0,0,0,0)!important}
.button-item:nth-child(n) .item-style{background-color:var(--link-button-border-bg-color)!important;border-radius:0!important;border:2px dashed var(--link-button-border-color)!important;box-shadow:none}
.item-style:hover{box-shadow:none;transform:none}
.item-style .ctm-style{margin:0;border:0}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color)}`,'style5.border':`.cmpt-button-buttonLink .show-sortNum::before{left:-34px}
.item-style .ctm-style::after,.item-style .ctm-style::before,.item-style::after,.item-style::before{display:none;background:0 0;transform:none;border:0}
.item-style .ctm-style{border:0!important}
.button-item:nth-child(n) .item-style{background-color:rgba(0,0,0,0)!important;border-radius:0;border:2px solid transparent!important;box-shadow:none}
.item-style:hover{box-shadow:none;transform:none}
.item-style::before{position:absolute;top:6px;left:-8px;content:"";display:block;width:8px;height:100%;background:var(--link-button-bg-color)}
.item-style::after{position:absolute;bottom:-8px;right:8px;content:"";display:block;width:100%;height:8px;background:var(--link-button-bg-color)}
.item-style .ctm-style{margin:0;background-color:rgba(0,0,0,0)!important;border-radius:0;border:2px solid var(--link-button-bg-border-color)!important}
.item-style .ctm-style:before{position:absolute;top:-2px;left:-10px;content:"";display:block;width:0;height:0;border-bottom:6px solid var(--link-button-bg-border-color);border-left:8px solid transparent}
.item-style .ctm-style:after{position:absolute;bottom:-10px;right:-2px;content:"";display:block;width:0;height:0;border-top:8px solid var(--link-button-bg-border-color);border-right:8px solid transparent}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color)}`,'style6.border':`.cmpt-button-buttonLink .show-sortNum::before{left:-34px}
.item-style .ctm-style::after,.item-style .ctm-style::before,.item-style::after,.item-style::before{display:none;background:0 0;transform:none;border:0}
.button-item:nth-child(n) .item-style{background-color:rgba(0,0,0,0)!important;border-radius:0;border:2px solid transparent!important;box-shadow:none;}
.item-style:hover{box-shadow:none;transform:none}
.item-style::before{position:absolute;top:6px;left:-8px;content:"";display:block;width:2px;height:100%;background:var(--link-button-border-color)}
.item-style::after{position:absolute;bottom:-7px;right:8px;content:"";display:block;width:100%;height:2px;background:var(--link-button-border-color)}
.item-style .ctm-style{margin:0;background-color:rgba(0,0,0,0)!important;border-radius:0;border:2px solid var(--link-button-border-color)!important}
.item-style .ctm-style:before{position:absolute;top:1px;left:-10px;content:"";display:block;width:10px;height:2px;background:var(--link-button-border-color);transform:rotate(-36deg)}
.item-style .ctm-style:after{position:absolute;bottom:-6px;right:-2px;content:"";display:block;width:10px;height:2px;background:var(--link-button-border-color);transform:rotate(-45deg)}
.item .btn-icon span{border:2px solid var(--link-button-border-thumbnail-border-color);color:var(--link-button-border-thumbnail-color)}`,'radius0.border.shadow':`.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important;background-color:transparent;}
.item{border-radius:0!important;background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-shadow-color)!important;box-shadow:var(--link-button-shadow-color) 12px 12px 0px 0px;margin-bottom:20px}
.item-style:hover{transform:translate(4px, 4px);box-shadow:var(--link-button-shadow-color) 8px 8px 0px 0px;}`,'radius12.border.shadow':`.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important;background-color:transparent;}
.item{border-radius:12px!important;background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-shadow-color)!important;box-shadow:var(--link-button-shadow-color) 12px 12px 0px 0px;margin-bottom:20px}
.item-style:hover{transform:translate(4px, 4px);box-shadow:var(--link-button-shadow-color) 8px 8px 0px 0px;}`,'radius50.border.shadow':`.item-style::before,.item-style::after,.item-style .ctm-style::before,.item-style .ctm-style::after{display:none;background:transparent;transform:none;border:0;}
.item-style .ctm-style{border:0!important;background-color:transparent;}
.item{border-radius:50vh!important;background-color:var(--link-button-bg-color)!important;border:2px solid var(--link-button-shadow-color)!important;box-shadow:var(--link-button-shadow-color) 12px 12px 0px 0px;margin-bottom:20px}
.item-style:hover{transform:translate(4px, 4px);box-shadow:var(--link-button-shadow-color) 8px 8px 0px 0px;}`,},'iconStyle':{'radius0':'.item .btn-icon img, .item .btn-icon span,.button-item .left .item img,.button-item>.item>img{border-radius:0!important;}','radius':'.item .btn-icon img, .item .btn-icon span,.button-item .left .item img,.button-item>.item>img{border-radius:var(--link-button-radius12, 8px)!important;}','radius12':'.item .btn-icon img, .item .btn-icon span,.button-item .left .item img,.button-item>.item>img{border-radius:var(--link-button-radius12, 8px)!important;}','radius50':'.item .btn-icon img, .item .btn-icon span,.button-item .left .item img,.button-item>.item>img{border-radius:50%!important;}'},'text_color':`.button-item:nth-child(n) .item .btn .btn-text,.button-item:nth-child(n) .item .btn-text .link-text{color:{0}!important}
        body{--link-button-font-color:{0};--link-button-border-font-color:{0};}`,'color':`--link-button-bg-color:{0};--link-button-bg-border-color:{0};--link-button-border-color:{0};`,'color1':'--link-button-shadow-color:{0};','opacity':'{}',},BIO_Theme_2_CSS_PageBg={'color':'section .section-bg{background-image:initial;background-color:{0};}','gradient':{'gradient.style.flat':'--link-page-bg-gradient-style:to right;','gradient.style.up':'--link-page-bg-gradient-style:to bottom;','gradient.style.down':'--link-page-bg-gradient-style:to top;','gradient.color.default':`section .section-bg{}`,'gradient.color.color1':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #EF629F, #EECDA3)}`,'gradient.color.color2':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #F64F59, #C471ED, #12C2E9)}`,'gradient.color.color3':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #FDBB2D, #22C1C3)}`,'gradient.color.color4':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #1D2671, #C33764)}`,'gradient.color.color5':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #2C3E50, #BDC3C7)}`,'gradient.color.color6':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #B91D73, #F953C6)}`,'gradient.color.color7':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #C6FFDD, #FBD786, #F7797D)}`,'gradient.color.color8':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #0083B0, #00B4DB)}`,'gradient.color.color9':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #185A9D, #43CEA2)}`,'gradient.color.color10':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #870000, #190A05 35%)}`,'gradient.color.color11':`section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), #EEF2F3, #8E9EAB)}`,},'common':'section .section-bg{border-radius:{0}px;opacity:{1};}section{border-radius:{0}px;}'},BIO_Theme_2_CSS_Layout3={style:{'backgroundColor':`--link-block-bg-color:{0};`,'borderColor':'--link-block-border-color:{0};','textColor':'--link-block-font-color:{0};--link-title-color:{0};--link-text-desc-color:{0};','corner':'--link-block-corner:{0}px;',},button:{backgroundColor:`--link-action-bg-color:{0};`,textColor:`--link-action-font-color:{0};`,},},BIO_Theme_2_CSS_Thumbnail={'style':{'origin':`.item .btn-icon img{display:block;}
    .item .btn-icon span{display:none;}`,'borderColor':`.item .btn-icon img{display:none;}
              .item .btn-icon span{display:block;}`},'radius':{'radius0':'.item .btn-icon img,.item .btn-icon span{border-radius:0!important;}','radius':'.item .btn-icon img,.item .btn-icon span{border-radius:var(--link-button-radius12, 8px)!important;}','radius12':'.item .btn-icon img,.item .btn-icon span{border-radius:var(--link-button-radius12, 8px)!important;}','radius50':'.item .btn-icon img,.item .btn-icon span{border-radius:50%!important;}'},'color':`--link-button-bg-thumbnail-color:{0};
    --link-button-bg-thumbnail-border-color:{0};
    --link-button-border-thumbnail-color:{0};
    --link-button-border-thumbnail-border-color:{0};
`,},Theme_2_CSS_Social={'style':{'default':'','origin':'[class^=cmpt-social] li a img{display:block;}\n[class^=cmpt-social] li a span{display:none;}','borderColor':'[class^=cmpt-social] li a img{display:none;}\n[class^=cmpt-social] li a span{display:block;}'},'radius':{'radius0':'[class^=cmpt-social] li a img,[class^=cmpt-social] li a span{border-radius:0!important;}','radius':'[class^=cmpt-social] li a img,[class^=cmpt-social] li a span{border-radius:var(--link-social-radius, 8px)!important;}','radius12':'[class^=cmpt-social] li a img,[class^=cmpt-social] li a span{border-radius:var(--link-social-radius, 8px)!important;}','radius50':'[class^=cmpt-social] li a img,[class^=cmpt-social] li a span{border-radius:50%!important;}'},'color':'--link-social-color:{0};\n--link-social-border-color:{0};',},Theme_2_CSS_Style={align:'section [class^=cmpt-]{text-align:{0}}\nsection [class^=cmpt-] [class*=ctm-style-],section [class*=ctm-style-] .image-bg{text-align:{0};margin-left:auto;margin-right:auto;margin-{0}:0;}\n[class^=cmpt-] ul.social_list{justify-content:{0};justify-content:{1}}',spacing:'section .content [class^=cmpt-]{margin-top:{0}px;}',},Theme_2_CSS_Tab={color:'.tab_box1 ul li a{color:{0};}',selectedColor:'.tab_box1 ul li.selected i,.tab_box1 ul li.selected span{color:{0};}',backgroundColor:'.tab_box1{background-color:{0}}',font:'.tab_box1{font-family:"{0}";}',size:'',tab_position:{1:'.tab_box1 li a span{display:block}\n.tab_box1 li a i,.tab_box1 li a img{display:block}',2:'.tab_box1 li a span{display:none}\n.tab_box1 li a i,.tab_box1 li a img{display:block}',3:'.tab_box1 li a span{display:block}\n.tab_box1 li a i,.tab_box1 li a img{display:none!important}'}},Theme_2_CSS_Menu={color:'.tab_box2 ul li a,.side_dark .icon-close{color:{0};}',selectedColor:'.tab_box2 li.selected a{color:{0};}',backgroundColor:'.side_dark{background-color:{0}}',font:'.tab_box2{font-family:"{0}";}',size:''},Theme_2_CSS_Logo={shape:{rectangle:'.header img{border-radius:0;}',circle:'.header img{border-radius:50%;}'},size:'.header .image-box{width:{size}px;height:{size}px;}section .header{height:{size}px;line-height:{size}px}',corner:'.header img{border-radius:{corner}px;}',width:'.header .image-box{width:{width}px;}',height:'.header .image-box{height:{height}px;}section .header{height:{height}px;line-height:{height}px}',},Theme_2_CSS_Text={color:'section .header h6{color:{0};}',align:'section .header h6{text-align:{align}!important}',font:'section .header h6{font-family:{font}!important;}',fontSize:'section .header h6{font-size:{fontSize}px}',fontWeight:'section .header h6{font-weight:{fontWeight}}',letterSpacing:'section .header h6{letter-spacing:{letterSpacing}px}',};var _IMAGE_DOMAIN='https://bio.linkcdn.cc/';function _int(num){num=parseInt(num,10);if(isNaN(num))return 0;return num;}
function _parse_style(style,m){var _HIDE_RE_COMPILE=/\.hide(-(\w+))+/ig,_HIDE_RE_COMPILE_MATCH=/-(\w+)/ig;style=(typeof style!=='undefined')?style:'';m=(typeof m!=='undefined')?m:'hide';if(m=='hide'&&style.indexOf('.hide-')!=-1){if(_HIDE_RE_COMPILE.test(style))return _HIDE_RE_COMPILE_MATCH.exec(style);}
return[];}
function _hex2rgb(color,opacity,style){opacity=(typeof opacity!=='undefined')?opacity:null;style=(typeof style!=='undefined')?style:'';if(!isEmpty(color)){color=(color?color:'000000')+'';color=color.replace('#','');opacity=isEmpty(opacity)?1:_int(opacity)/100;if(opacity<=0)return 'rgba(0,0,0,0)';if(color.length==3){return 'rgba({r},{g},{b},{a})'.Compile({r:color[0],g:color[1],b:color[2],a:opacity.toFixed(3)})}
if(color.length==4){return 'rgba({r},{g},{b},{a})'.Compile({r:color[0],g:color[1],b:color[2],a:(parseInt(color[3]+color[3],16)/255).toFixed(3)})}
if(color.length==6){return 'rgba({r},{g},{b},{a})'.Compile({r:parseInt(color.substr(0,2),16),g:parseInt(color.substr(2,2),16),b:parseInt(color.substr(4,2),16),a:opacity.toFixed(3)})}
if(color.length==8){return 'rgba({r},{g},{b},{a})'.Compile({r:parseInt(color.substr(0,2),16),g:parseInt(color.substr(2,2),16),b:parseInt(color.substr(4,2),16),a:(parseInt(color.substr(4,2),16)/255).toFixed(3)})}}
return 'rgba(0,0,0,0)';}
function _format_color(color){if(!isEmpty(color)){if(typeof color=='number')color=(color?color:'000000')+'';if(color.startsWith('rgba(')){var _color_val=color.replace('rgba(','');if(_color_val.endsWith(')'))_color_val=_color_val.slice(0,-1);_color_val=_color_val.split(',');if(_color_val.length==3)return 'rgba({0}, {1}, {2}, 1)'.Format(_color_val[0],_color_val[1],_color_val[2]);if(_color_val.length==4)return 'rgba({0}, {1}, {2}, {3})'.Format(_color_val[0],_color_val[1],_color_val[2],_color_val[3]);return color;}
if(color.startsWith('rgb(')){_color_val=color.replace('rgb(','');if(_color_val.endsWith(')'))_color_val=_color_val.slice(0,-1);_color_val=_color_val.split(',');if(_color_val.length==3)return 'rgb({0}, {1}, {2})'.Format(_color_val[0],_color_val[1],_color_val[2]);if(_color_val.length==4)return 'rgba({0}, {1}, {2}, {3})'.Format(_color_val[0],_color_val[1],_color_val[2],_color_val[3]);return color}
if(color.startsWith('#'))return color;if(isNaN(parseInt(color,16)))return color;if(!color.startsWith('#'))return '#'+color;return color}
return ''}
function _check_image(link,w,h){if(link){if(link.indexOf('.fotoee.com')!=-1)link=link.replace(/(upload\.statics|instabio\.cdn)\.fotoee\.com/,'bio.linkcdn.cc');if(link.indexOf('bio.linkcdn.to')!=-1)link=link.replace(/bio\.linkcdn\.cc/,'bio.linkcdn.cc');if(link.indexOf('bio.linkcdn.cc')!=-1)link=link.split('?')[0];if(!link.startsWith('http'))link=_IMAGE_DOMAIN+link;if(link.indexOf('bio.linkcdn.cc')!=-1&&(w||h)){return link+'?imageView2/2'+(w?'/w/'+w:'')+(h?'/h/'+'h':'');}}
return(link||'');}
var ThemeConfigTheme=function(data){var val=(data||{}).value||{};this.font=val.font;this.textColor=val.textColor;this._fields=['font','textColor'];};ThemeConfigTheme.prototype={as_css:function(textConf){var _text=BIO_Theme_2_CSS_Text,_this=this;var _css_list=[];try{textConf=textConf||{};var x='font',xVal=_this.font;if(textConf.value&&(textConf.value[x]||textConf.value['font-family'])){if(isEmpty(xVal))xVal=textConf.value[x]||textConf.value['font-family'];}
if(!isEmpty(xVal))_css_list.push(_text['font1'].Format(_this[x]));x='textColor';xVal=_this.textColor;if(isEmpty(xVal)&&textConf.value)xVal=textConf.value.color;if(!isEmpty(xVal))_css_list.push(_text['color1'].Format(_format_color(xVal)));}catch(e){}
return[_css_list,[]]},};var ThemeConfigLayout3=function(data){var _value=data||{};this.style=_value.style||{};this.button=_value.button||{};this._fields=['style','button'];};ThemeConfigLayout3.prototype={as_css:function(){var _layout=BIO_Theme_2_CSS_Layout3,_this=this;var _css_list=['body .block-box,body .block-item{'],_css_var_list=[];try{var x='style',_x_dict;if(_this.style&&_layout[x]){_x_dict=_layout[x];if(!isEmpty(_this.style.backgroundColor))_css_list.push(_x_dict.backgroundColor.Format(_hex2rgb(_this.style.backgroundColor,_this.style.opacity)));if(!isEmpty(_this.style.borderColor))_css_list.push(_x_dict.borderColor.Format(_format_color(_this.style.borderColor)));if(!isEmpty(_this.style.textColor))_css_list.push(_x_dict.textColor.Format(_format_color(_this.style.textColor)));if(!isEmpty(_this.style.corner))_css_list.push(_x_dict.corner.Format(_this.style.corner));}
x='button';if(_this.button&&_layout[x]){_x_dict=_layout[x];if(!isEmpty(_this.button.backgroundColor))_css_list.push(_x_dict.backgroundColor.Format(_format_color(_this.button.backgroundColor)));if(!isEmpty(_this.button.textColor))_css_list.push(_x_dict.textColor.Format(_format_color(_this.button.textColor)));}}catch(e){}
_css_list.push('}')
return[_css_list,_css_var_list];},};var ThemeConfig=function(data,image){this.modules=[];this.text=null;this.theme=null;this.layout3=null;var _this=this;image=(typeof image!=='undefined')?image:'';(data||[]).forEach(function(x,idx){if(x.template){if(x.module=='bgImg')_this.modules.push(new ThemeConfigBackground(x.template,image));else if(x.module=='pageBg')_this.modules.push(new ThemeConfigPageBg(x.template));else if(x.module=='theme'&&x.template.value)_this.theme=new ThemeConfigTheme(x.template);else if(x.module=='layout3')_this.modules.push(new ThemeConfigLayout3(x.template));else if(x.module=='textFont'||x.module=='buttonFont'){if(__data.bio.part>=3)_this.text=new ThemeConfigText(x.template);else _this.modules.push(new ThemeConfigText(x.template));}
else if(x.module=='button'&&(x.template||{}).key=='buttonIcon'){if(__data.bio.part==1){_this.button=new ThemeConfigButton(x.template);}}else if(x.module=='thumbnail'){if(__data.bio.part==1){_this.thumbnail=new ThemeConfigThumbnail(x.template);}}else if(x.module=='social')_this.modules.push(new ThemeConfigMedia(x.template));else if(x.module=='style')_this.modules.push(new ThemeConfigStyle(x.template));else if(x.module=='tab')_this.modules.push(new ThemeConfigTab(x.template));else if(x.module=='menu')_this.modules.push(new ThemeConfigMenu(x.template));else if(x.module=='logo')_this.modules.push(new ThemeConfigLogo(x.template));else if(x.module=='sitename')_this.modules.push(new ThemeConfigSiteName(x.template));else _this.modules.push(new ThemeConfigBasic(x.template,x.module));}});this._fields=['text','button','background','page'];};ThemeConfig.prototype={as_css:function(){var _css_list=[],_css_var_list=['body{'];this.modules.forEach(function(x,idx){var x_ret=x.as_css();_css_list=_css_list.concat(x_ret[0]);_css_var_list=_css_var_list.concat(x_ret[1]);});var x_ret=[];if(this.theme){x_ret=this.theme.as_css(this.text);_css_list=_css_list.concat(x_ret[0]);_css_var_list=_css_var_list.concat(x_ret[1]);}else if(this.text){x_ret=this.text.as_css();_css_list=_css_list.concat(x_ret[0]);_css_var_list=_css_var_list.concat(x_ret[1]);}
if(this.button){x_ret=this.button.as_css();_css_list=_css_list.concat(x_ret[0]);_css_var_list=_css_var_list.concat(x_ret[1]);}
if(this.thumbnail){x_ret=this.thumbnail.as_css();_css_list=_css_list.concat(x_ret[0]);_css_var_list=_css_var_list.concat(x_ret[1]);}
_css_var_list.push('}');return _css_var_list.join('\n')+_css_list.join('\n');},};var ThemeConfigBasic=function(data,m){this.module=m;this.key=data.key;this.value=data.value||{};this._fields=['key','opacity','blur','image'];};ThemeConfigBasic.prototype={as_css:function(){var _css_list=[],_css_var_list=[],_this=this;try{_css_list.push('{0}{'.Format(BIO_ALIAS_2_CSS[this.module]));var _tem_css=[];Object.keys(this.value).forEach(function(k,idx){var v=_this.value[k];if(!isEmpty(v)&&!_this._fields.includes(k)){if(k=='color'&&_this.module=='button'){_tem_css.push('{0}{'.Format(BIO_ALIAS_2_CSS.link));_tem_css.push("{0}:{1};".Format(k,v));_tem_css.push('}');}
if(k=='link-color'&&_this.module=='button'){_tem_css.push('{0}{'.Format(BIO_ALIAS_2_CSS[k]));_tem_css.push("{0}: {1};".Format('color',v));_tem_css.push('}')}
if(k=='border-radius'&&_this.module=='button'){v=v||'';if(v.indexOf('!important')<0)v=v+'!important';}
if(k.indexOf('Font')!=-1||k.indexOf('font-family')!=-1){_css_list.push("{0}: '{1}';".Format(k,v))}else{_css_list.push("{0}: {1};".Format(k,v))}}});_css_list.push('}');_css_list=_css_list.concat(_tem_css);}catch(e){}
return[_css_list,_css_var_list];},};var ThemeConfigBackground=function(data,image){this._keys=['bgImgColor','bgImgGradient','bgImgCtm','bgImgDefault','bgImgVideo'];this.image=image||'';this.key=data.key;this.bgHeader=data.bgHeader;if(this.key&&this._keys.includes(this.key))this.module=data.value||{};this._fields=['key','module'];};ThemeConfigBackground.prototype={as_css:function(){if(this.bgHeader&&(__data||{bio:{}}).bio.part==9){return this.bgHeader_css();}else if(this.key=='bgImgColor'){return this.color_css();}else if(this.key=='bgImgGradient'){return this.gradient_css();}else if(this.key=='bgImgCtm'){return this.image_css();}else if(this.key=='bgImgDefault'){return this.image_css();}else if(this.key=='bgImgVideo'){return this.video_css();}
return[[],[]];},bgHeader_css:function(){var _background=BIO_Theme_2_CSS_Background,_this=this;var _css_list=[],_css_var_list=[];if(_this.bgHeader.style=='color'){if(_this.bgHeader.color)_css_list.push(_background.color.Format(_format_color(_this.bgHeader.color)));}else{if(_this.bgHeader.image)_css_list.push(_background.image.style['upload'].Format(_check_image(_this.bgHeader.image)));}
if(_this.module&&_this.module.color)_css_list.push(_background.container.color.Format(_format_color(_this.module.color)));return[_css_list,_css_var_list];},color_css:function(){var _background=BIO_Theme_2_CSS_Background,_this=this;var _css_list=[],_css_var_list=[];try{if(_this.module.color)_css_list.push(_background.color.Format(_format_color(_this.module.color)));}catch(e){}
return[_css_list,_css_var_list];},gradient_css:function(){var _background=BIO_Theme_2_CSS_Background,_this=this.module;var _css_list=[],_css_var_list=[];try{if(!isEmpty(_this.direction)&&!isEmpty(_this.color1)&&!isEmpty(_this.color2)){var _css='.bg div{background-image:linear-gradient(var(--link-background-gradient-style), {0}, {1}{2})}.bg video{display:none}';if(isNaN(_this.direction)){if(_background.gradient[_this.direction]){_css_var_list.push(_background.gradient[_this.direction]||'');_css_list.push(_css.Format(_format_color(_this.color1),_format_color(_this.color2),_this.color3?','+_format_color(_this.color3):''))}else{if(_this.direction=='outIn'){_css='.bg div{background-image:radial-gradient({3}{2}{1}, {0})}.bg video{display:none}';_css_list.push(_css.Format(_format_color(_this.color1)+(_this.color3?'':' 80%'),_format_color(_this.color2),_this.color3?_format_color(_this.color3)+',':'',_this.color3?'circle,':''))}else{_css='.bg div{background-image:radial-gradient({3}{0}, {1}{2})}.bg video{display:none}';_css_list.push(_css.Format(_format_color(_this.color1),_format_color(_this.color2),_this.color3?','+_format_color(_this.color3):' 80%',_this.color3?'circle,':''))}}}else{_css_var_list.push('--link-background-gradient-style:{0}deg;'.Format(_this.direction));_css_list.push(_css.Format(_format_color(_this.color1),_format_color(_this.color2),_this.color3?','+_format_color(_this.color3):''))}}else{if(_this.style)_css_var_list.push(_background.gradient[_this.style]||'');if(_this.gradient)_css_list.push(_background.gradient[_this.gradient]||'')}}catch(e){}
return[_css_list,_css_var_list];},image_css:function(){var _background=BIO_Theme_2_CSS_Background,_this=this;var _css_list=[],_css_var_list=[];try{if(_this.module.image)_css_list.push(_background.image.style[_this.module.style||'default'].Format(_check_image(_this.module.image)));_css_var_list.push(_background.image.blur.Format(_int(_this.module.blur)));_css_var_list.push(_background.image.opacity.Format(_int(_this.module.opacity)/100))}catch(e){}
return[_css_list,_css_var_list];},video_css:function(){var _background=BIO_Theme_2_CSS_Background,_this=this;var _css_list=[],_css_var_list=[];try{if(_this.module.videoImage||_this.module.link)_css_list.push(_background.video.coverr.Format(_check_image(_this.module.videoImage)));if(_this.module.link){d.querySelector('.bg-container .bg div').innerHTML='<video autoplay="" playsinline="" loop="" muted="" poster="{0}" src="{1}"><source src="{1}" type="video/map4"></video>'.Format(_this.module.videoImage,_this.module.link)}}catch(e){}
return[_css_list,_css_var_list];}};var ThemeConfigPageBg=function(data){this._keys=['pageBgColor','pageBgGradient'];this.key=data.key;this.module=data.value||{};};ThemeConfigPageBg.prototype={as_css:function(){if(this.key=='pageBgColor'){return this.color_css();}else if(this.key=='pageBgGradient'){return this.gradient_css();}else{return this._common_css([],[]);}},_common_css:function(css_list,css_var_list){var _background=BIO_Theme_2_CSS_PageBg,_this=this;css_list=css_list||[];css_var_list=css_var_list||[];try{var corner=parseInt(_this.module.corner,10),opacity=parseFloat(_this.module.opacity)/100;if(!(isNaN(corner)&&isNaN(opacity)))css_list.push(_background.common.Format(isNaN(corner)?'':corner,isNaN(opacity)?'':opacity));}catch(e){}
return[css_list,css_var_list];},color_css:function(){var _background=BIO_Theme_2_CSS_PageBg,_this=this;var _css_list=[],_css_var_list=[];try{if(_this.module.color)_css_list.push(_background.color.Format(_format_color(_this.module.color)));return _this._common_css(_css_list,_css_var_list);}catch(e){}
return[_css_list,_css_var_list];},gradient_css:function(){var _background=BIO_Theme_2_CSS_PageBg,_this=this.module;var _css_list=[],_css_var_list=[];try{if(!isEmpty(_this.direction)&&!isEmpty(_this.color1)&&!isEmpty(_this.color2)){var _css='section .section-bg{background-image:linear-gradient(var(--link-page-bg-gradient-style), {0}, {1}{2})}.bg video{display:none}';if(isNaN(_this.direction)){if(_background.gradient[_this.direction]){_css_var_list.push(_background.gradient[_this.direction]||'');_css_list.push(_css.Format(_format_color(_this.color1),_format_color(_this.color2),_this.color3?','+_format_color(_this.color3):''))}else{if(_this.direction=='outIn'){_css='section .section-bg{background-image:radial-gradient({3}{2}{1}, {0})}.bg video{display:none}';_css_list.push(_css.Format(_format_color(_this.color1)+(_this.color3?'':' 80%'),_format_color(_this.color2),_this.color3?_format_color(_this.color3)+',':'',_this.color3?'circle,':''))}else{_css='section .section-bg{background-image:radial-gradient({3}{0}, {1}{2})}.bg video{display:none}';_css_list.push(_css.Format(_format_color(_this.color1),_format_color(_this.color2),_this.color3?','+_format_color(_this.color3):' 80%',_this.color3?'circle,':''))}}}else{_css_var_list.push('--link-page-bg-gradient-style:{0}deg;'.Format(_this.direction));_css_list.push(_css.Format(_format_color(_this.color1),_format_color(_this.color2),_this.color3?','+_format_color(_this.color3):''))}}else{if(_this.style)_css_var_list.push(_background.gradient[_this.style]||'');if(_this.gradient)_css_list.push(_background.gradient[_this.gradient]||'');}
return this._common_css(_css_list,_css_var_list);}catch(e){}
return[_css_list,_css_var_list];}};var ThemeConfigButton=function(data){this.key=data.key;this.value=data.value||{};this._fields=['key','buttonStyle','iconStyle','text_color','color','opacity'];};ThemeConfigButton.prototype={as_css:function(){var _button=BIO_Theme_2_CSS_Button,_this=this;var _css_list=[],_css_var_list=[];try{['buttonStyle','iconStyle'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_button[x];_css_list.push(_x_dict[_this.value[x]])}});var _ver=(__data.ui.version||'3.0.0').replace(/v/i,'');['color'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_button[x];if(parseFloat(_ver)>=3.3){_css_var_list.push(_x_dict.Format(_hex2rgb(_this.value[x],_this.value.opacity)))}else{_css_var_list.push(_x_dict.Format(_hex2rgb(_this.value[x])))}}});['text_color'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_button[x];_css_list.push(_x_dict.Format(_format_color(_this.value[x])))}});['color1'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_button[x];_css_var_list.push(_x_dict.Format(_format_color(_this.value[x])))}});}catch(e){}
return[_css_list,_css_var_list];},};var ThemeConfigThumbnail=function(data){this.key=data.key;var _value=data.value||{};this.style=_value.style;this.radius=_value.radius;this.color=_format_color(_value.color);this._fields=['key','style','radius','color'];};ThemeConfigThumbnail.prototype={as_css:function(){var _thumbnail=BIO_Theme_2_CSS_Thumbnail,_this=this;var _css_list=[],_css_var_list=[];try{['style','radius'].forEach(function(x,idx){if(_this[x]&&_thumbnail[x]){var _x_dict=_thumbnail[x];_css_list.push(_x_dict[_this[x]])}});var _x='color';if(_this[_x]&&_thumbnail[_x]){var _x_dict=_thumbnail[_x];_css_var_list.push(_x_dict.Format(_this[_x]));}}catch(e){}
return[_css_list,_css_var_list];},};var ThemeConfigMedia=function(data){this.key=data.key;var _value=data.value||{};this.style=_value.style;this.radius=_value.radius;this.color=_format_color(_value.color);this._fields=['key','style','radius','color'];};ThemeConfigMedia.prototype={as_css:function(){var _social=Theme_2_CSS_Social,_this=this;var _css_list=[],_css_var_list=[];try{['style','radius'].forEach(function(x,idx){if(_this[x]&&_social[x]){var _x_dict=_social[x];_css_list.push(_x_dict[_this[x]])}});var _x='color';if(_this[_x]&&_social[_x]){var _x_dict=_social[_x];_css_var_list.push(_x_dict.Format(_this[_x]));}}catch(e){}
return[_css_list,_css_var_list];},};var ThemeConfigText=function(data){this.key=data.key;var _val=data.value||{};this.value=data.value||{};this.font=_val.font;Object.defineProperty(this,'font-family',{value:_val['font-family'],writable:true,enumerable:true,configurable:true});this.color=_format_color(_val.color);this._fields=['key','value'];};ThemeConfigText.prototype={as_css:function(){var _text=BIO_Theme_2_CSS_Text,_this=this;var _css_list=[];try{['font','font-family',"color"].forEach(function(x,idx){if(_this.hasOwnProperty(x)&&_this[x]){_css_list.push(_text[x].Format(_this[x]))}});}catch(e){}
return[_css_list,[]]},};var ThemeConfigStyle=function(data){this.key=data.key;var _val=data.value||{};this.value=_val;this.align=_val.align;this.spacing=_val.spacing;this._fields=['align','spacing'];};ThemeConfigStyle.prototype={as_css:function(){var _style=Theme_2_CSS_Style,_this=this;var _css_list=[];try{var _x='align';if(_this.hasOwnProperty(_x)&&!isEmpty(_this[_x])){var _xv=_this[_x];if(_xv=='left')_xv='flex-start';if(_xv=='right')_xv='flex-end';_css_list.push(_style[_x].Format(_this[_x],_xv))}
['spacing'].forEach(function(x,idx){if(_this.hasOwnProperty(x)&&!isEmpty(_this[x])){_css_list.push(_style[x].Format(_this[x]))}});}catch(e){}
return[_css_list,[]]},};var ThemeConfigTab=function(data){this.key=data.key;var _val=data.value||{};this.value=data.value||{};this.color=_format_color(_val.color);this.selectedColor=_format_color(_val.selectedColor);this.backgroundColor=_format_color(_val.backgroundColor);this.font=_val.font;this.size=_val.size;this.tab_position=_val.tab_position;this._fields=['color','selectedColor','backgroundColor','font','size'];};ThemeConfigTab.prototype={as_css:function(){var _text=Theme_2_CSS_Tab,_this=this;var _css_list=[];try{['color','selectedColor',"backgroundColor","font","size"].forEach(function(x,idx){if(_this.hasOwnProperty(x)&&!isEmpty(_this[x])){_css_list.push(_text[x].Format(_this[x]))}});var _x='tab_position';if(!isEmpty(_this[_x])&&_text[_x]){_css_list.push(_text[_x][_this[_x]]);}}catch(e){}
return[_css_list,[]]},};var ThemeConfigMenu=function(data){this.key=data.key;var _val=data.value||{};this.value=data.value||{};this.color=_format_color(_val.color);this.selectedColor=_format_color(_val.selectedColor);this.backgroundColor=_format_color(_val.backgroundColor);this.font=_val.font;this.size=_val.size;this._fields=['color','selectedColor','backgroundColor','font','size'];};ThemeConfigMenu.prototype={as_css:function(){var _text=Theme_2_CSS_Menu,_this=this;var _css_list=[];try{['color','selectedColor',"backgroundColor","font","size"].forEach(function(x,idx){if(_this.hasOwnProperty(x)&&_this[x]){_css_list.push(_text[x].Format(_this[x]))}});}catch(e){}
return[_css_list,[]]},};var ThemeConfigLogo=function(data){this.key=data.key;var _val=data.value||{};this.value=data.value||{};this.shape=_val.shape;this.size=_val.size;this.corner=_val.corner;this.width=_val.width;this.height=_val.height;};ThemeConfigLogo.prototype={as_css:function(){var _text=Theme_2_CSS_Logo,_this=this;var _css_list=[];try{var _v='shape';if(!isEmpty(_this.value[_v]))_css_list.push(_text.shape[_this.value[_v]]);if(_this.value[_v]=='circle'){['size'].forEach(function(v,i){if(_text[v]&&!isEmpty(_this.value[v])){var _v={};_v[v]=_this.value[v];_css_list.push(_text[v].Compile(_v));}});}else if(_this.value[_v]=='rectangle'){['corner','width','height'].forEach(function(v,i){if(_text[v]&&!isEmpty(_this.value[v])){var _v={};_v[v]=_this.value[v];_css_list.push(_text[v].Compile(_v));}});}}catch(e){}
return[_css_list,[]]},};var ThemeConfigSiteName=function(data){this.key=data.key;var _val=data.value||{};this.value=data.value||{};this.shape=_val.shape;this.size=_val.size;this.corner=_val.corner;this.width=_val.width;this.height=_val.height;};ThemeConfigSiteName.prototype={as_css:function(){var _text=Theme_2_CSS_Text,_this=this;var _css_list=[];try{['fontSize','fontWeight','letterSpacing','font','align'].forEach(function(v,i){if(_text[v]&&!isEmpty(_this.value[v])){var _v={};_v[v]=_this.value[v];_css_list.push(_text[v].Compile(_v));}});var _v='color';if(!isEmpty(_this.value[_v]))_css_list.push(_text.color.Format(_format_color(_this.value[_v])));}catch(e){}
return[_css_list,[]]},};(function(){var _pathLink=document.querySelector('link[data-path]');var _path=_pathLink?_pathLink.dataset.path:'';if(_path.startsWith('animate_')){var js,fjs=d.getElementsByTagName('script')[0];js=d.createElement('script');js.async=!0;js.src='https://bio.linkcdn.cc/instabio.cc/static/js/'+_path+'.js?t=1632706094845';fjs.parentNode.insertBefore(js,fjs);}
try{var _theme_config=new ThemeConfig(__theme||[]);var _style=d.createElement('style');_style.type='text/css';d.querySelector('head').appendChild(_style);_style.innerHTML=_theme_config.as_css();}catch(e){}
_pathLink.media='all';})();var Lfy_Form_Theme_Style={style:{border:`{cssid} .form-cust .form-control input,{cssid} .form-cust .form-control select,{cssid} .form-cust .form-control textarea,{cssid} .form-cust .form-field-phone .dial-code,.form-cust .form-control .form-field-file-upload{border:2px solid var(--form-style-color);background:transparent;}`,background:`{cssid} .form-cust .form-control input,{cssid} .form-cust .form-control select,{cssid} .form-cust .form-control textarea,{cssid} .form-cust .form-field-phone .dial-code,.form-cust .form-control .form-field-file-upload{border:2px solid transparent;background:var(--form-style-color);}`,underline:`{cssid} .form-cust .form-control input,{cssid} .form-cust .form-control select,{cssid} .form-cust .form-control textarea,{cssid} .form-cust .form-field-phone .dial-code,.form-cust .form-control .form-field-file-upload{border:2px solid transparent;background:transparent;border-bottom:2px solid var(--form-style-color);border-right:0;border-left:0;border-radius:0;}
        {cssid} .form-cust .form-field-phone .dial-code{border-left:0;border-radius:0;}`,},color:`--form-style-color:{0};`,corner:`{1} .form-cust .form-control input,{1} .form-cust .form-control select,{1} .form-cust .form-control textarea,{1} .form-cust .form-button button,.form-cust .form-control .form-field-file-upload{border-radius:{0}px}
    {1} .form-cust .form-field-phone .dial-code{border-top-left-radius:{0}px;border-bottom-left-radius:{0}px;}`,},Lfy_Form_Theme_Background={color:'--form-bg-color:{0};--form-border-color:{0};',corner:'{1} .form-cust{border-radius:{0}px}',style:{background:`{0} .form-cust{background:var(--form-bg-color)!important;border:0!important;}`,border:`{0} .form-cust{background:rgba(0,0,0,0)!important;border:2px solid var(--form-border-color)!important;}`},},Lfy_Form_Theme_Text={font:'--form-tmpl-font:{0};',color:`--form-text-color:{0};`,color1:`--form-title-color:{0};`,},Lfy_Form_Theme_Submit={style:{border:`{cssid} .form-cust .form-button button{background:transparent;border:2px solid var(--form-submit-color);}`,background:`{cssid} .form-cust .form-button button{background:var(--form-submit-color);border:2px solid transparent;}`,},color:`--form-submit-color:{0};`,color1:`--form-submit-font-color:{0};`,corner:`{0} .form-cust .form-button button{border-radius:{1}px}`,};window.FormThemeConfig=function(data,eleId){this.configs=[];this.eleId=eleId?('#'+eleId):'';var _this=this;if(data){if(!Array.isArray(data)){data=[data];}
data.forEach(function(item,idx){if(item.module)item=item.template;if(item.key=='style')_this.configs.push(new FormThemeConfigStyle(item.value));if(item.key=='background')_this.configs.push(new FormThemeConfigBackground(item.value));if(item.key=='text')_this.configs.push(new FormThemeConfigText(item.value));if(item.key=='submit')_this.configs.push(new FormThemeConfigSubmit(item.value));});}
this._fields=['style','background','text','submit'];this._cssDom=d.querySelector('#style-form-tmpl');if(!this._cssDom){this._cssDom=document.createElement('style');this._cssDom.id='style-form-tmpl';document.head.appendChild(this._cssDom);}};FormThemeConfig.prototype={as_css:function(){var _css_list=[],_css_var_list=['body {0},{0} .block-box{'.Format(this.eleId)],_this=this;_this.configs.forEach(function(x,idx){var x_ret=x.as_css(_this.eleId);_css_list=_css_list.concat(x_ret[0]);_css_var_list=_css_var_list.concat(x_ret[1]);});_css_var_list.push('}');_this._cssDom.innerHTML+=_css_list.join('\n');_this._cssDom.innerHTML+=_css_var_list.join('\n');},};var FormThemeConfigStyle=function(data){this.value=data||{};this._fields=['style','color','corner'];};FormThemeConfigStyle.prototype={as_css:function(eleId){var _style=Lfy_Form_Theme_Style,_this=this;var _css_list=[],_css_var_list=[];try{['corner'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_style[x];_css_list.push(_x_dict.Format(_this.value[x],eleId));}});['style'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_style[x];_css_list.push(_x_dict[_this.value[x]].Compile({cssid:eleId}))}});['color'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_style[x];_css_var_list.push(_x_dict.Format(_format_color(_this.value[x])))}});}catch(e){}
return[_css_list,_css_var_list];},};var FormThemeConfigBackground=function(data){this.value=data||{};this._fields=['style','color','opacity','corner'];};FormThemeConfigBackground.prototype={as_css:function(eleId){var _bg=Lfy_Form_Theme_Background,_this=this;var _css_list=[],_css_var_list=[];['corner'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_bg[x];_css_list.push(_x_dict.Format(_this.value[x],eleId));}});var x='color',_x_dict;if(!isEmpty(_this.value[x])){_x_dict=_bg[x];_css_var_list.push(_x_dict.Format(_hex2rgb(_this.value[x],_this.value.opacity)))}
x='style';if(!isEmpty(_this.value[x])){_x_dict=_bg[x];_css_list.push(_x_dict[_this.value[x]].Format(eleId))}
return[_css_list,_css_var_list];}};var FormThemeConfigText=function(data){this.value=data||{};this._fields=['font','color','color1'];};FormThemeConfigText.prototype={as_css:function(eleId){var _text=Lfy_Form_Theme_Text,_this=this;var _css_list=[],_css_var_list=[];try{['font'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_text[x];_css_var_list.push(_x_dict.Format(_this.value[x]))}});['color','color1'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_text[x];_css_var_list.push(_x_dict.Format(_format_color(_this.value[x])))}});}catch(e){}
return[_css_list,_css_var_list];},};var FormThemeConfigSubmit=function(data){this.value=data||{};this._fields=['style','color','color1'];};FormThemeConfigSubmit.prototype={as_css:function(eleId){var _button=Lfy_Form_Theme_Submit,_this=this;var _css_list=[],_css_var_list=[];try{['style'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_button[x];_css_list.push(_x_dict[_this.value[x]].Compile({cssid:eleId}))}});['color','color1'].forEach(function(x,idx){if(!isEmpty(_this.value[x])){var _x_dict=_button[x];_css_var_list.push(_x_dict.Format(_format_color(_this.value[x])))}});var _v='corner';if(!isEmpty(_this.value[_v])){_css_list.push(_button[_v].Format(eleId,_this.value[_v]));}}catch(e){}
return[_css_list,_css_var_list];},};}(document));